### ISSUE TITLE
Design READme

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/DSA-with-Kunal#14]
Design a beautiful readme for this repo.

**Comment by asdsyd** [comment]
@Mubashir061 do you want this issue?

**Comment by Mubashir-Md** [comment]
Yeah sure, would love to...Can you provide the details for this like should I write down the topics with their algorithm explanations or what exactly..

**Comment by asdsyd** [comment]
Alright, issue assigned:)

**Comment by asdsyd** [comment]
Just a brief info of what this repo is. List algos etc in a beautiful design

**Comment by Mubashir-Md** [comment]
Okay...I'll do it
