### ISSUE TITLE
links not working in roadmap.md file

### ISSUE THREAD

**Issue by shaikamirgh** [asdsyd/DSA-with-Kunal#22]
I think I can fix that

**Comment by asdsyd** [comment]
Which links? They are working fine I checked.

**Comment by shaikamirgh** [comment]
below ones aren't . 
from stacks and queues

**Comment by asdsyd** [comment]
![Screenshot 2022-10-27 at 3 49 48 PM](https://user-images.githubusercontent.com/77977076/198259588-cdbd0e82-be9b-4c57-a462-b7d68659c7c4.png)

You mean the later ones in white? Those are to be covered by Kunal himself. He has to record those videos yet.

**Comment by asdsyd** [comment]
I have a new issue in Healthy Dev you might want to check it out. Thanks.

**Comment by shaikamirgh** [comment]
oh, ok.
