### ISSUE TITLE
Make that box checklist roadmap.

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/DSA-with-Kunal#3]
In initial videos of kunal, he had shown his dsa roadmap topics with a checklist box so we can keep a track of. Find that and put in this repo to keep track of your dsa learning path. Use github for _learning in public_ even tho you can do it locally in your laptop.

**Comment by aryanbk** [comment]
I can work on this work on this. _I'm thinking to add Syllabus(roadmap) to readme as well as a to add separate roadmap.md file in repo._

**Comment by asdsyd** [comment]
@aryanbk Alright go ahead.

**Comment by asdsyd** [comment]
Thank you for contributing. 🚀
